# Generated by Django 5.0.3 on 2024-03-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='miModelo',
            new_name='miModelp',
        ),
    ]
