# Generated by Django 5.0.3 on 2024-03-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_mimodelo_mimodelp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='miModelp',
            new_name='miModelo',
        ),
    ]
