# Generated by Django 5.0.3 on 2024-03-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_mimodelp_mimodelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='miModelo',
            new_name='miModeloTable',
        ),
    ]
