# Generated by Django 5.0.3 on 2024-03-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_mimodelo_mimodelotable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimodelotable',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mimodelotable',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
